# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment,
# skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs
# as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-gh-pages:
    runs-on:
      - ubuntu-latest

    steps:
      # Creating files to be published to GitHub Pages
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run build --if-present
      - run: npm test

      # Published on GitHub Pages
      - name: Push gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Deploy keys and Personal access Tokens are also available
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
          # If keep_files is set to true, 
          # you can suppress the behavior that all files are deleted once on each git push.
          keep_files: false
          user_name: github-actions
          user_email: github-actions@github.com
